title: Koteswarudu Akula
description: Software Engineer specializing in high-performance backend systems and mobile SDKs
baseurl: ""
url: "https://akula-koteswarudu.github.io"

# Theme - using remote_theme for better compatibility
remote_theme: pages-themes/cayman@v0.2.0

# Social links
github_username: akula-koteswarudu
linkedin_username: koteswarudu-akula-7087921a4

# SEO
author: Koteswarudu Akula
twitter:
  username: your-twitter # optional
  card: summary

# Plugins (only GitHub Pages supported ones)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock